/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.c3;

import it.unicam.cs.ids.c3.javafx.JavaFXC3;
import it.unicam.cs.ids.c3.database.DBManager;
import javafx.application.Application;

import java.io.IOException;
import java.sql.SQLException;

public class App {
    public static void main(String[] args) throws IOException, SQLException {
        DBManager.getInstance().setDBManager("root", "toor");
        launchGui();
    }
    private static void launchGui() {
        Application.launch(JavaFXC3.class);
    }
}