/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.c3;

import it.unicam.cs.ids.c3.javafx.JavaFXC3;
import it.unicam.cs.ids.c3.model.*;
import it.unicam.cs.ids.c3.services.DBManager;
import it.unicam.cs.ids.c3.services.SerializerAggiunta;
import it.unicam.cs.ids.c3.services.SerializerElimina;
import it.unicam.cs.ids.c3.services.SerializerModifica;
import javafx.application.Application;
import org.checkerframework.checker.units.qual.C;

import java.io.IOException;
import java.sql.SQLException;
import java.util.GregorianCalendar;

public class App {
    public static void main(String[] args) throws IOException, SQLException {
        DBManager.getInstance().setDBManager("root", "toor");
        launchGui();
    }
    private static void launchGui() {
        Application.launch(JavaFXC3.class);
    }
}