/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.c3;

import it.unicam.cs.ids.c3.javafx.JavaFXC3;
import javafx.application.Application;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        launchGui();
    }

    private static void launchGui() {
        Application.launch(JavaFXC3.class);
    }
}
