/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.ids.c3;

import it.unicam.cs.ids.c3.model.Recensione;

import java.util.UUID;

public class App {
    public static void main(String[] args) {
        Recensione recensione = new Recensione("tutto ok");
        System.out.print(recensione.getID());
        System.out.print("ifyegfiuefvewufvw");

    }
}
